### ISSUE TITLE
Building VirtualBox kernel modules with Clang and DKMS

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/linux#1104]
Hi,

I don't know where to report this, but...let me try :) feel free to close if it's the wrong place.

So I finally managed to build current 5.7.10 kernel with `LLVM=1 LLVM_IAS=1` with clang11 from the `release/11.x` branch, and the IAS related patches I found (among others) here: https://github.com/ClangBuiltLinux/linux/issues/1049 ,
and which I assembled together here: https://github.com/torvic9/linux57-vd/blob/master/0006-clang-llvm-ias-support.patch

The problem is that I cannot build the VBox host modules using `CC=clang LD=ld.lld`. I get the following errors:
```
./arch/x86/include/asm/page_64.h:49:2: error: expected '(' after 'asm'
        alternative_call_2(clear_page_orig,
        ^
/arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^

./arch/x86/include/asm/special_insns.h:212:2: error: expected '(' after 'asm'
        alternative_io(".byte " __stringify(NOP_DS_PREFIX) "; clflush %P0",
        ^
```

and many more of the same type.

Compiling the kernel with clang10 and without LLVM_IAS results in working VBox modules.

Is this an issue with the fact that I used LLVM_IAS for the kernel? 
Or is it rather related to using clang11 instead of clang10?

Thanks!

**Comment by dileks** [comment]
`LLVM_IAS=1` is still categorized `EXPERIMENTAL`.

Unfortunately, you forgot about some important informations which might help.
What (snapshot) versions of clang-10 and clang-11?
What version of virtualbox?

As said in #1049:
`Linux v5.8-rcX` together with `LLVM_IAS=1` is a good choice.
Doing some `-no-integrated-as` workarounds helped but not in any case with `Linux v5.7.y`.
As you have seen by yourself it depends also on the clang version.

Compiling/assembling `LLVM_IAS=1` plus `LLVM=1` is another story.

Currently, I use this kernel-release:
```
$ cat /proc/version 
Linux version 5.8.0-rc6-4-amd64-llvm11-ias (sedat.dilek@gmail.com@iniza) (clang version 11.0.0 (https://github.com/llvm/llvm-project cebd637c88624dfd44520848cb1f43dc8a02ba80), LLD 11.0.0 (https://github.com/llvm/llvm-project cebd637c88624dfd44520848cb1f43dc8a02ba80)) #4~bullseye+dileks1 SMP 2020-07-22
```
...with some additional patches - the one to support `LLVM_IAS=1` are in my series: 5 patches.

Unsure - when I will update #1049 - but Linux v5.7.y is no more on my radar or interest.
I have Debian's 5.7.6 plus my Linux 5.8-rcX (LLVM_IAS=1 + LLVM=1) kernel installed.

Parts like "elfcore: build with -no-integrated-as when LLVM_IAS=1" I published in #1049.
Some parts (diffs) I do not know where you have it from and what it is fixing.

Without further informations you are at your own...

**Comment by nickdesaulniers** [comment]
> The problem is that I cannot build the VBox host modules

What config is that?

**Comment by dileks** [comment]
Updated #1049.

[1] https://github.com/ClangBuiltLinux/linux/issues/1049#issuecomment-662609378

**Comment by torvic9** [comment]
Here is the version info:
`clang version 11.0.0 (git://github.com/llvm/llvm-project 8f8ec9927623eb54f003993b3d8411fc0130ca90)`

I'm not sure it's the IAS. The modules cannot be built either way with the clang version mentioned above, i.e. with the kernel built with/without IAS. The kernel itself builds, installs and runs just fine.

Is it possible thatt additional flags have to be passed to the VBox make command?

What works is clang10(rc4) without IAS, on the same kernel+config.

**Comment by ihalip** [comment]
> What config is that?

VirtualBox modules are out-of-tree.

**Comment by dileks** [comment]
We have  parts of "VBOX" in-tree - depending on your Linux-kernel version :-) - not a full support like VirtualBox upstream.
```
$ grep VBOX /boot/config-5.8.0-rc6-4-amd64-llvm11-ias 
CONFIG_DRM_VBOXVIDEO=m
CONFIG_VBOXGUEST=m
CONFIG_VBOXSF_FS=m
```

Here on Debian we have `virtualbox-dkms` to build out-of-tree with `DKMS`.

**Comment by torvic9** [comment]
Yes, I mean the out-of-tree host modules (vboxdrv etc.).
I also use dkms to build them, with the following make command added to dkms.conf:

`MAKE[0]='make CC=clang LD=ld.lld KERNELRELEASE=${_kernver}'`
(_kernver is of course the kernel version)

**Comment by dileks** [comment]
I am building a new kernel and will try with `virtualbox-dkms` version `6.1.12-dfsg-6` from Debian/unstable after it has finished.

**Comment by torvic9** [comment]
Thanks!
You're right, I forgot some info.
VBox version is 6.1.12.
clang10 is: `clang version 10.0.1 (git://github.com/llvm/llvm-project 77d76b71d7df39b573dfa1e391096a040e9b7bd3)`
clang11 is: `clang version 11.0.0 (git://github.com/llvm/llvm-project 8f8ec9927623eb54f003993b3d8411fc0130ca90)`

> Some parts (diffs) I do not know where you have it from and what it is fixing.

The only part that I didn't get from here is the last diff, which eliminates `__force_order` errors I encountered.
Here's the link to LKML: https://lore.kernel.org/r/20200527135329.1172644-1-arnd@arndb.de/

I'm aware that IAS is still experimental, I'm just trying out a few things (and, as you can see, I don't have the required knowledge...). I have not yet moved to 5.8.

I'm typing this from 5.7.10 built with `LLVM=1 LLVM_IAS=1`:
`Linux version 5.7.10-1-vd (linux57-vd@manjaro) (clang-vd clang version 11.0.0 (git://github.com/llvm/llvm-project 8f8ec9927623eb54f003993b3d8411fc0130ca90)`

I can paste the logfile from the failed module building process if that helps.

**Comment by nickdesaulniers** [comment]
Ah! out of tree/dkms. Yeah, that's not tested.  IIRC, @ColinIanKing mentioned being able to work around this.  @ColinIanKing do you remember the particular issue you saw with DKMS?

@torvic9 how do we fetch this out of tree code, and invoke a build of it?

**Comment by dileks** [comment]
You need linux-headers packages installed:
```
# dpkg -l | grep linux-headers | awk '/^ii/ {print $1 " " $2 " " $3}' | column -t
ii  linux-headers-5.7.0-1-amd64   5.7.6-1
ii  linux-headers-5.7.0-1-common  5.7.6-1
ii  linux-headers-amd64           5.7.6-1
```

Install VBox DKMS package, build+install and check DKMS status:
```
# apt update && apt install virtualbox-dkms

# dpkg -l | grep dkms | awk '/^ii/ {print $1 " " $2 " " $3}' | column -t
ii  acpi-call-dkms   1.1.0-6
ii  dkms             2.8.2-2
ii  virtualbox-dkms  6.1.12-dfsg-6

# dkms install -m virtualbox -v 6.1.12 -k 5.7.0-1-amd64

# dkms status
acpi-call, 1.1.0, 5.7.0-1-amd64, x86_64: installed
virtualbox, 6.1.12, 5.7.0-1-amd64, x86_64: installed
```

**Comment by dileks** [comment]
```
$ sudo dpkg -i linux-headers-5.8.0-rc6-6-amd64-llvm11-ias_5.8.0~rc6-6~bullseye+dileks1_amd64.deb

$ sudo dkms build -m virtualbox -v 6.1.12 -k 5.8.0-rc6-6-amd64-llvm11-ias

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-rc6-6-amd64-llvm11-ias -C /lib/modules/5.8.0-rc6-6-amd64-llvm11-ias/build M=/var/lib/dkms/virtualbox/6.1.12/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.0-rc6-6-amd64-llvm11-ias (x86_64)
Consult /var/lib/dkms/virtualbox/6.1.12/build/make.log for more information.
```
[make-log_vbox-6-1-12_llvm11-ias.txt](https://github.com/ClangBuiltLinux/linux/files/4967777/make-log_vbox-6-1-12_llvm11-ias.txt)

**Comment by dileks** [comment]
My hack was to add a temporary symlink `/path/to/clang-$VER` ->  `/usr/bin/gcc`.

**Comment by dileks** [comment]
With that hack:
```
# cd /usr/bin/
# mv gcc gcc.orig
# ln -sf clang-11 gcc

# dkms build -m virtualbox -v 6.1.12 -k 5.8.0-rc6-6-amd64-llvm11-ias            

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-rc6-6-amd64-llvm11-ias -C /lib/modules/5.8.0-rc6-6-amd64-llvm11-ias/build M=/var/lib/dkms/virtualbox/6.1.12/build......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.0-rc6-6-amd64-llvm11-ias (x86_64)
Consult /var/lib/dkms/virtualbox/6.1.12/build/make.log for more information.

# cat /var/lib/dkms/virtualbox/6.1.12/build/make.log
DKMS make.log for virtualbox-6.1.12 for kernel 5.8.0-rc6-6-amd64-llvm11-ias (x86_64)
Thu Jul 23 19:36:14 CEST 2020
make: Entering directory '/usr/src/linux-headers-5.8.0-rc6-6-amd64-llvm11-ias'
  CC [M]  /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrvSem.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrvTracer.o
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
    RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
                                     ^
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:38: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:760:17: error: initializing 'RTCCUINTREG' (aka 'unsigned long long') with an expression of incompatible type 'void'
    RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
                ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
        this_cpu_write(cpu_tlbstate.cr4, uNew);
                       ^
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.c:764:24: error: use of undeclared identifier 'cpu_tlbstate'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/linux/SUPDrv-linux.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub() is missing an ELF size annotation
make[1]: *** [scripts/Makefile.build:497: /var/lib/dkms/virtualbox/6.1.12/build/vboxdrv] Fehler 2
make: *** [Makefile:1762: /var/lib/dkms/virtualbox/6.1.12/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.8.0-rc6-6-amd64-llvm11-ias'
```

**Comment by dileks** [comment]
The problem is in DKMS code:
```
3614: # Unset environment variables that may interfere with the build
3615: unset CC CXX CFLAGS CXXFLAGS LDFLAGS
```

[1] https://github.com/dell/dkms/blob/master/dkms#L3614

**Comment by torvic9** [comment]
> My hack was to add a temporary symlink `/path/to/clang-$VER` -> `/usr/bin/gcc`.

I worked around it by adding the make command with `CC=clang` to dkms.conf (see above).

**Comment by dileks** [comment]
@torvic9 ah cool.

Hmm, you need to add all `$MAKE_OPTS` from your make line of the kernel-build including `LLVM_IAS=1` and `LLVM=1`?

**Comment by dileks** [comment]
> Edit: however your error messages are completely different to the asm errors?

I have some additional `x86/asm` patches in my series and Linux `v5.8-rc6`.
Cannot say which VBox version supports it.

**Comment by torvic9** [comment]
I only added CC.
I'm now rebuilding clang11 and will try again, however still on 5.7. Will switch to 5.8 soon though.

Where can I find your current series?

**Comment by dileks** [comment]
That's the minimal patchset:

https://github.com/ClangBuiltLinux/linux/issues/1049#issuecomment-662609378

**Comment by torvic9** [comment]
Hmm...
On 5.8-rc6, I still need the initram and elfnote patches.
Also, for some reason, applying the crc32 patch results in "unknown mnemonic". 
Interestingly enough, it seems that it doesn't know either `movzxw` or `movzxq` mnemonics.
What's happening there??

**Comment by torvic9** [comment]
(I deleted my previous comment as it was just a typo)

**Comment by dileks** [comment]
There are two different version of @arndb crc32c patch - the original [1] is for Linux 5.8 - I published an adapted version for Linux v5.7.

[1] https://git.kernel.org/herbert/cryptodev-2.6/c/44623b2818f4a442726639572f44fd9b6d0ef68c

**Comment by dileks** [comment]
Depending on your `llvm-toolchain` (here: `release/11.x` Git) - the patches you mentioned are no more necessary.
In my last posting in #1043 I displayed the version I used.

**Comment by torvic9** [comment]
> Depending on your `llvm-toolchain` (here: `release/11.x` Git) - the patches you mentioned are no more necessary.

Here: git-release/11.x from July 21st. Still necessary.
I haven't updated the toolchain yet due to a problem with the build-llvm.py script (I'll open an issue there).

To get back on topic: I still encounter the same ASM related errors on 5.8-rc6 when compiling VBox host modules 6.1.12.

**Comment by dileks** [comment]
Nice to see you use our tools like `tc-build` and infrastructure :-).

As said https://github.com/llvm/llvm-project/commit/cebd637c88624dfd44520848cb1f43dc8a02ba80 fixed for me all recent `Linux/x86` problems reported in the CBL issue-tracker. So, I will keep this version for a while.
Maybe till there is an official `llvmorg-11.0.0-rc1` release tag.

[1] https://github.com/ClangBuiltLinux/tc-build/issues/104
[2] https://github.com/llvm/llvm-project/tags

**Comment by dileks** [comment]
> > Depending on your `llvm-toolchain` (here: `release/11.x` Git) - the patches you mentioned are no more necessary.
> 
> Here: git-release/11.x from July 21st. Still necessary.

Be precise as possible via `clang -v`.
The output displays a unique `commit-id` when build from Git.

**Comment by dileks** [comment]
You looked at `https://github.com/llvm/llvm-project/commit/833f8c958601bb640ba6a25d627c1dc58dad14d2`?

**Comment by torvic9** [comment]
> Be precise as possible via `clang -v`.

I did, maybe you missed it: `clang version 11.0.0 (git://github.com/llvm/llvm-project 8f8ec9927623eb54f003993b3d8411fc0130ca90)`

I'll build a new toolchain later and report back; this laptop doesn't have enough processing power for a PGO build...

> Nice to see you use our tools like `tc-build` and infrastructure :-).

Sure, it's fun experimenting with clang :) I hope I can get a better knowledge about it. Technically I don't have any real use for it.

**Comment by dileks** [comment]
Hehe, it's CPU power plus enough RAM (and/or SWAP) for PGO and/or Thin-LTO.

BTW, I am doing a `stage1-only` build.

**Comment by nickdesaulniers** [comment]
ok, let's report then to the DKMS developers. Let's find their bug tracker.

**Comment by dileks** [comment]
@nickdesaulniers 

This is a known issue which I reported as "dkms: Build with an alternative like compiler rather than gcc" to debian-kernel ML in July 2018.

Mario Limonciello pointed me to the above lines in the dkms source.

It does not hurt to report to dkms upstream but as @torvic9 pointed out you can override/pass individual `make options` via/to `dkms.conf`.
( Untested by /me. )

[1] https://lists.debian.org/debian-kernel/2018/07/subject.html

**Comment by torvic9** [comment]
The issue is **not** related to `LLVM_IAS=1`.

With 5.8-rc6 and clang-11 `3c1fca803bc14617b67ba2125e1b4b77190e9f86`, I get the same ASM errors with and without IAS.

However, using instead clang-10 `77d76b71d7df39b573dfa1e391096a040e9b7bd3`, I do not get these ASM errors, instead I have similar error messages as in @dileks comment above.

It seems that the host modules are not yet fully supported, a similar bug report can be found here:
https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1884652 (see log file)

**Comment by torvic9** [comment]
Here are some patches to make VBox 6.1.12 host modules compatible with kernel 5.8.
I have only tried with gcc so far, but they seem to build correctly.
There is one patch for the kernel itself, and 3 patches for the host modules.

https://www.virtualbox.org/ticket/19644

**Comment by dileks** [comment]
That means be patient - wait for `VBox` version `6.1.13` which will have support for `Linux-kernel` version `5.8`.

**Comment by dileks** [comment]
[1] says:
```
virtualbox (6.1.12-dfsg-8) unstable; urgency=medium

  * debian/patches/kernel-5.8-1.patch:
  * debian/patches/kernel-5.8-2.patch:
  * debian/patches/kernel-5.8-3.patch:
    - apply upstream proposed patches to fix a build failure with kernel 5.8
      (note, this requires also a kernel patch)
      https://www.virtualbox.org/ticket/19644

 -- Gianfranco Costamagna <locutusofborg@debian.org>  Thu, 30 Jul 2020 18:58:32 +0200
```

[1] https://metadata.ftp-master.debian.org/changelogs//contrib/v/virtualbox/virtualbox_6.1.12-dfsg-8_changelog

**Comment by dileks** [comment]
Missing patch against `Linux v5.8-rc7`:
```diff
diff --git a/mm/vmalloc.c b/mm/vmalloc.c
--- a/mm/vmalloc.c
+++ b/mm/vmalloc.c
@@ -315,6 +315,7 @@ int map_kernel_range_noflush(unsigned long addr, unsigned long size,
 
        return 0;
 }
+EXPORT_SYMBOL(map_kernel_range);
 
 int map_kernel_range(unsigned long start, unsigned long size, pgprot_t prot,
                struct page **pages)
@@ -2129,6 +2130,7 @@ struct vm_struct *__get_vm_area_caller(unsigned long size, unsigned long flags,
        return __get_vm_area_node(size, 1, flags, start, end, NUMA_NO_NODE,
                                  GFP_KERNEL, caller);
 }
+EXPORT_SYMBOL(__get_vm_area_caller);
 
 /**
  * get_vm_area - reserve a contiguous kernel virtual area
```

**Comment by dileks** [comment]
VBox patches against Linux v5.8-rcX:

1. https://sources.debian.org/src/virtualbox/6.1.12-dfsg-8/debian/patches/
1. https://sources.debian.org/data/contrib/v/virtualbox/6.1.12-dfsg-8/debian/patches/kernel-5.8-1.patch
1. https://sources.debian.org/data/contrib/v/virtualbox/6.1.12-dfsg-8/debian/patches/kernel-5.8-2.patch
1. https://sources.debian.org/data/contrib/v/virtualbox/6.1.12-dfsg-8/debian/patches/kernel-5.8-3.patch

**Comment by torvic9** [comment]
Thanks. Already applied all 4 directly from vbox site, i.e. put them in PKGBUILDs (vbox and kernel). No missing patch there. Builds fine with rc7 and gcc. Clang not tested yet.

**Comment by dileks** [comment]
@torvic9 

Good.
I will try with the kernel-patch only as Debian/unstable has the 3 other ones.
Here it's 36 degrees Celsius @18:02 so I will do build this night.

**Comment by torvic9** [comment]
35° here :) good luck. I'll try with clang as well and report back.

**Comment by dileks** [comment]
I was able to build a Vbox kernel-modules with my `gcc-symlink trick`.
Need some more playing with `dkms.conf`.

**Comment by dileks** [comment]
Passing `LLVM_IAS=1" results in:
```
  AR      /var/lib/dkms/virtualbox/6.1.12/build/built-in.a
  MODPOST /var/lib/dkms/virtualbox/6.1.12/build/Module.symvers
ERROR: modpost: "__force_order" [/var/lib/dkms/virtualbox/6.1.12/build/vboxdrv/vboxdrv.ko] undefined!
```

Patch from @arndb <https://lkml.org/lkml/2020/5/27/766>

**Comment by dileks** [comment]
With this diff:
```diff       
--- /usr/src/virtualbox-6.1.12/dkms.conf.orig   2020-07-30 18:58:32.000000000 +0200
+++ /usr/src/virtualbox-6.1.12/dkms.conf        2020-08-01 11:57:36.420490455 +0200
@@ -1,5 +1,6 @@
 PACKAGE_NAME="virtualbox"
 PACKAGE_VERSION="6.1.12"
+MAKE="make CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 LLVM_IAS=1 -C /lib/modules/5.8.0-rc7-6-amd64-llvm11-ias/build M=/var/lib/dkms/virtualbox/6.1.12/build"
 CLEAN="rm -f *.*o"
 BUILT_MODULE_NAME[0]="vboxdrv"
 BUILT_MODULE_LOCATION[0]="vboxdrv"
```

Build VBox kernel-modules:
```
root@iniza:~# LC_ALL=C dkms build -m virtualbox -v 6.1.12 -k 5.8.0-rc7-6-amd64-llvm11-ias              

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-rc7-6-amd64-llvm11-ias CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 LLVM_IAS=1 -C /lib/modules/5.8.0-rc7-6-amd64-llvm11-ias/build M=/var/lib/dkms/virtualbox/6.1.12/build.........................
cleaning build area...

DKMS: build completed.
```

Install VBox kernel-modules:
```
root@iniza:~# LC_ALL=C dkms install -m virtualbox -v 6.1.12 -k 5.8.0-rc7-6-amd64-llvm11-ias
```

Check DKMS status:
```
root@iniza:~# dkms status -m virtualbox
virtualbox, 6.1.12, 5.8.0-rc7-6-amd64-llvm11-ias, x86_64: installed
```

Check status of `virtualbox.service` and start it:
```
root@iniza:~# systemctl status virtualbox.service 
● virtualbox.service - LSB: VirtualBox Linux kernel module
     Loaded: loaded (/etc/init.d/virtualbox; generated)
     Active: inactive (dead)
       Docs: man:systemd-sysv-generator(8)

root@iniza:~# systemctl status virtualbox.service 
● virtualbox.service - LSB: VirtualBox Linux kernel module
     Loaded: loaded (/etc/init.d/virtualbox; generated)
     Active: active (exited) since Sat 2020-08-01 12:00:41 CEST; 8min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 8247 ExecStart=/etc/init.d/virtualbox start (code=exited, status=0/SUCCESS)

Aug 01 12:00:41 iniza systemd[1]: Starting LSB: VirtualBox Linux kernel module...
Aug 01 12:00:41 iniza virtualbox[8247]: Loading VirtualBox kernel modules... vboxdrv vboxnetflt vboxnetadp.
Aug 01 12:00:41 iniza systemd[1]: Started LSB: VirtualBox Linux kernel module.
```

Check loaded VBox kernel-modules:
```
root@iniza:~# lsmod | grep vbox
vboxnetadp             28672  0
vboxnetflt             32768  0
vboxdrv               520192  2 vboxnetadp,vboxnetflt
```

Check dmesg-outputs:
```
root@iniza:~# LC_ALL=C dmesg -T | tail
[Sat Aug  1 11:47:13 2020] wlp1s0: associate with 50:d4:f7:2e:17:da (try 1/3)
[Sat Aug  1 11:47:13 2020] wlp1s0: RX AssocResp from 50:d4:f7:2e:17:da (capab=0x411 status=0 aid=1)
[Sat Aug  1 11:47:13 2020] wlp1s0: associated
[Sat Aug  1 11:47:13 2020] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0: link becomes ready
[Sat Aug  1 12:00:40 2020] vboxdrv: loading out-of-tree module taints kernel.
[Sat Aug  1 12:00:40 2020] vboxdrv: Found 4 processor cores
[Sat Aug  1 12:00:40 2020] vboxdrv: TSC mode is Invariant, tentative frequency 1597812133 Hz
[Sat Aug  1 12:00:40 2020] vboxdrv: Successfully loaded version 6.1.12_Debian (interface 0x002d0001)
[Sat Aug  1 12:00:40 2020] VBoxNetFlt: Successfully started.
[Sat Aug  1 12:00:40 2020] VBoxNetAdp: Successfully started.
```

**Comment by dileks** [comment]
New VBox `dkms.conf` diff:
```diff
--- /usr/src/virtualbox-6.1.12/dkms.conf.orig   2020-07-30 18:58:32.000000000 +0200
+++ /usr/src/virtualbox-6.1.12/dkms.conf        2020-08-01 13:06:54.522773507 +0200
@@ -1,6 +1,11 @@
 PACKAGE_NAME="virtualbox"
 PACKAGE_VERSION="6.1.12"
-CLEAN="rm -f *.*o"
+CC_FOR_BUILD="CC=clang-11"
+LD_FOR_BUILD="LD=ld.lld-11"
+LLVM_UTILS="AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11"
+MAKE_OPTS="${CC_FOR_BUILD} ${LD_FOR_BUILD} ${LLVM_UTILS} LLVM_IAS=1"
+MAKE[0]="make V=1 ${MAKE_OPTS} -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
+CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
 BUILT_MODULE_NAME[0]="vboxdrv"
 BUILT_MODULE_LOCATION[0]="vboxdrv"
 DEST_MODULE_LOCATION[0]="/updates"
```

**Comment by dileks** [comment]
Full VBox `dkms.conf`:
```
[ /usr/src/virtualbox-6.1.12/dkms.conf ]

PACKAGE_NAME="virtualbox"
PACKAGE_VERSION="6.1.12"
CC_FOR_BUILD="CC=clang-11"
LD_FOR_BUILD="LD=ld.lld-11"
LLVM_UTILS="AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11"
MAKE_OPTS="${CC_FOR_BUILD} ${LD_FOR_BUILD} ${LLVM_UTILS} LLVM_IAS=1"
MAKE[0]="make V=1 ${MAKE_OPTS} -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
BUILT_MODULE_NAME[0]="vboxdrv"
BUILT_MODULE_LOCATION[0]="vboxdrv"
DEST_MODULE_LOCATION[0]="/updates"
BUILT_MODULE_NAME[1]="vboxnetadp"
BUILT_MODULE_LOCATION[1]="vboxnetadp"
DEST_MODULE_LOCATION[1]="/updates"
BUILT_MODULE_NAME[2]="vboxnetflt"
BUILT_MODULE_LOCATION[2]="vboxnetflt"
DEST_MODULE_LOCATION[2]="/updates"
AUTOINSTALL="yes"
```

**Comment by dileks** [comment]
I was able to import my `stretch-buildd.vmdk`, boot VM and shutdown.

**Comment by torvic9** [comment]
No luck here.
Still the same error messages as in OP:
```
In file included from ./arch/x86/include/asm/page.h:12:
./arch/x86/include/asm/page_64.h:49:2: error: expected '(' after 'asm'
        alternative_call_2(clear_page_orig,
        ^
```

Any ideas?

**Comment by dileks** [comment]
@torvic9 
I do not see this.
But I have some extra patches applied like from <tip.git#x86/asm>.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=x86/asm

**Comment by dileks** [comment]
I have sent an email to the `Debian virtualbox maintainers` and asked for an alternative handling of dkms.conf.

**Comment by torvic9** [comment]
I'm giving up on this one, it's not a big issue for me as I can just build with either clang-10 or gcc. 
I retried with binutils 2.35, `x86/asm` from tip as suggested, and a freshly built toolchain, but no... still the same ASM error messages, happens with every version of clang-11 I've tried.

**Comment by nickdesaulniers** [comment]
So this issue is only observed with clang-11, but not clang-10? If so, that's curious.  Are you building with both explicitly suffixed? Ie. `make CC=clang-11` and `make CC=clang-10` as opposed to `make CC=clang`?

**Comment by torvic9** [comment]
I'm using `LLVM=1` (and additionally `LLVM_IAS=1` with clang-11).

**Comment by nathanchance** [comment]
I have re-read this thread a couple times and I cannot follow it.

Is there any way to get a TL;DR with some commands to reproduce this issue locally? If this is a LLVM regression from 10.0.x to 11.0.x, we might have some time to get this fixed in ToT then backport to LLVM 11.0.0 before it ships. If not, we should ideally shoot for LLVM 11.0.1. We are committing to supporting the latest stable release from LLVM ([patch](https://lore.kernel.org/lkml/20200825222552.3113760-1-ndesaulniers@google.com/)) so it would be nice not to have a regression in LLVM 11 right off the bat :)

**Comment by torvic9** [comment]
Hi Nathan,

I have not tested it for some time now, but let me try to give you a TL;DR.
Please note that I'm not very knowledgeable about this topic, I cannot exclude the possibility that the error comes from my system.

1. build clang (here: with ThinLTO and PGO) with the `build-llvm.py` script using release-11.x branch
2. build the 5.8 kernel with that toolchain  (`make LLVM=1`)
3. use DKMS to build the VBox modules by passing `CC=clang LD=ld.lld` to DKMS' make command

Result: a lot of ASM related error messages as mentioned in OP. I can post the whole build log file later this week.

Instead, when using clang-10 from the Arch repos to build the kernel (version 10.0.1 at the time of writing), the VBox modules build just fine without errors.

Hope this helps.

**Comment by nathanchance** [comment]
I am starting to think this might be something with DKMS because it builds fine without it? If I am holding it wrong, let me know. I would like to avoid installing `virtualbox-dkms` on my server.

```
$ cd "$(mktemp -d)"

$ git clone https://github.com/ClangBuiltLinux/tc-build
...

$ tc-build/build-llvm.py --assertions --branch "release/11.x" --build-stage1-only --projects "clang;lld" --targets X86
...

$ curl -LSs https://download.virtualbox.org/virtualbox/6.1.12/VirtualBox-6.1.12a.tar.bz2 | tar -xjf -

$ curl -LSs https://github.com/archlinux/svntogit-community/raw/20aca7aca83f45bb1505c44955a3614d461f171f/trunk/021-linux-5-8.patch | patch -d VirtualBox-6.1.12 -p1
...

$ VirtualBox-6.1.12/src/VBox/HostDrivers/linux/export_modules.sh --folder vboxmod
VirtualBox-6.1.12/src/VBox/HostDrivers/linux/export_modules.sh: 120: [: Illegal number:
VirtualBox-6.1.12/src/VBox/HostDrivers/linux/export_modules.sh: 204: [: Illegal number:

$ curl -LSs https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.8.3.tar.xz | tar -xJf -

$ PATH=${PWD}/tc-build/build/llvm/stage1/bin:${PATH} make -C linux-5.8.3 -skj"$(nproc)" LLVM=1 defconfig bzImage

$ PATH=${PWD}/tc-build/build/llvm/stage1/bin:${PATH} make -C linux-5.8.3 -skj"$(nproc)" LLVM=1 M=${PWD}/vboxmod
/tmp/tmp.l1J0MXwOsz/vboxmod/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
/tmp/tmp.l1J0MXwOsz/vboxmod/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub() is missing an ELF size annotation
/tmp/tmp.l1J0MXwOsz/vboxmod/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyFrom()+0xe: redundant CLD
/tmp/tmp.l1J0MXwOsz/vboxmod/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyTo()+0xe: redundant CLD
WARNING: Symbol version dump "Module.symvers" is missing.
         Modules may not have dependencies or modversions.
WARNING: modpost: Symbol info of vmlinux is missing. Unresolved symbol check will be entirely skipped.

$ fd -e ko . vboxmod
vboxmod/vboxdrv/vboxdrv.ko
```

**Comment by torvic9** [comment]
I repeated your procedure, and effectively I don't get any errors either.
So it could be DKMS, or maybe even the kernel config?

**Comment by nathanchance** [comment]
It certainly could be configuration related. If you want to upload that, I can try it locally.

**Comment by torvic9** [comment]
I'm now trying with the default Arch config and I'll report back. I guess it's enough to build bzImage only, without the modules?

**Comment by nickdesaulniers** [comment]
@ColinIanKing I think mentioned encountering issues with DKMS when building with Clang.  I don't know the details, @ColinIanKing was that ever reported/resolved?

**Comment by dileks** [comment]
@torvic9 

Which version of `DKMS`?

**Comment by torvic9** [comment]
```
pacman -Qi dkms | grep -i vers                     
Version                  : 2.8.3-1
```

@nickdesaulniers , you probably mean this: https://github.com/dell/dkms/issues/124

**Comment by nickdesaulniers** [comment]
It would be good to have precise steps to reproduce; I'm not really familiar with DKMS, so it's not clear to me how to reproduce which is necessary to even get started.

**Comment by ColinIanKing** [comment]
I'll try and post some examples in the next day or so, the particular example we have is zfs from the zfsutils-linux debian or ubuntu source package.  But I'll try and  find some simpler examples that don't take forever.

**Comment by torvic9** [comment]
I've just tried this again, with VirtualBox 6.1.20 and DKMS.
Kernel 5.12 compiled with clang 12.0.1, running on Arch.

DKMS works with the following addition to `dkms.conf`:

```
LLVM_UTILS="CC=clang CXX=clang++ LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJSIZE=llvm-size STRIP=llvm-strip"
echo "MAKE[0]=\"make ${LLVM_UTILS} KERNELRELEASE=${_kernver}\"" >> $srcdir/dkms.conf
```
($_kernver simply points to a version file which contains the name of the kernel)

However, and this is quite remarkable, it only works when the kernel is NOT compiled with LTO.
With an LTO kernel, I get
`ld.lld: error: permission denied`
during the final linking phase, without any further explanation. I have no clue what's going on.

**Comment by ColinIanKing** [comment]
https://wiki.kubuntu.org/Kernel/Dev/DKMSPackaging is a good article on getting a simple hello world dkms example built

**Comment by ColinIanKing** [comment]
I built ubuntu 5.11.0-3 with clang, installed the kernel in Ubuntu 20.04 Hirsute and then tinkered with a simple hello world DKMS build using info from torvic9 (above).

https://kernel.ubuntu.com/~cking/hello-0.1.tar is a simple example DKMS demo that I put into /usr/src and then did:

```
sudo dkms add -m hello -v 0.1
sudo dkms build -m hello -v 0.1
sudo dkms install -m hello -v 0.1
sudo modprobe hello
```

So this works fine,  would be nice if dkms has the smarts to set the environment correctly for clang automatically

**Comment by dileks** [comment]
That `LLD ... permission denied` seems to be a local or distro specific problem.

Here I am successful:

```diff
root# git diff /usr/src/virtualbox-6.1.20/dkms.conf.orig /usr/src/virtualbox-6.1.20/dkms.conf
diff --git a/usr/src/virtualbox-6.1.20/dkms.conf.orig b/usr/src/virtualbox-6.1.20/dkms.conf
index eedda93..98bb523 100644
--- a/usr/src/virtualbox-6.1.20/dkms.conf.orig
+++ b/usr/src/virtualbox-6.1.20/dkms.conf
@@ -1,6 +1,13 @@
 PACKAGE_NAME="virtualbox"
 PACKAGE_VERSION="6.1.20"
-CLEAN="rm -f *.*o"
+LLVM_VER="12"
+CC_FOR_BUILD="clang-$LLVM_VER"
+LD_FOR_BUILD="ld.lld-$LLVM_VER"
+LLVM_UTILS="AR=llvm-ar-$LLVM_VER NM=llvm-nm-$LLVM_VER OBJCOPY=llvm-objcopy-$LLVM_VER OBJDUMP=llvm-objdump-$LLVM_VER READELF=llvm-readelf-$LLVM_VER STRIP=llvm-strip-$LLVM_VER"
+LLVM_IAS="LLVM_IAS=1"
+MAKE_OPTS="CC=${CC_FOR_BUILD} LD=${LD_FOR_BUILD} ${LLVM_UTILS} ${LLVM_IAS}"
+MAKE[0]="make V=1 ${MAKE_OPTS} -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
+CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
 BUILT_MODULE_NAME[0]="vboxdrv"
 BUILT_MODULE_LOCATION[0]="vboxdrv"
 DEST_MODULE_LOCATION[0]="/updates"
```

Building and installing `virtualbox`DKMS module with above modification (here: Clang-LTO built linux-image):
```sh
root# dkms build -m virtualbox -v 6.1.20 -k 5.12.0-1-amd64-clang12-lto

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.12.0-1-amd64-clang12-lto V=1 CC=clang-12 LD=ld.lld-12 AR=llvm-ar-12 NM=llvm-nm-12 OBJCOPY=llvm-objcopy-12 OBJDUMP=llvm-objdump-12 READELF=llvm-readelf-12 STRIP=llvm-strip-12 LLVM_IAS=1 -C /lib/modules/5.12.0-1-amd64-clang12-lto/build M=/var/lib/dkms/virtualbox/6.1.20/build.........................
cleaning build area...

DKMS: build completed.

root# dkms install -m virtualbox -v 6.1.20 -k 5.12.0-1-amd64-clang12-lto

vboxdrv.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.12.0-1-amd64-clang12-lto/updates/dkms/

vboxnetadp.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.12.0-1-amd64-clang12-lto/updates/dkms/

vboxnetflt.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.12.0-1-amd64-clang12-lto/updates/dkms/

depmod........

DKMS: install completed.
```

Listing new kernel-modules:
```
root# LC_ALL=C ll /lib/modules/5.12.0-1-amd64-clang12-lto/updates/dkms/
total 840K
drwxr-xr-x 2 root root 4.0K Apr 30 11:16 .
drwxr-xr-x 3 root root 4.0K Apr 30 11:16 ..
-rw-r--r-- 1 root root 746K Apr 30 11:16 vboxdrv.ko
-rw-r--r-- 1 root root  21K Apr 30 11:16 vboxnetadp.ko
-rw-r--r-- 1 root root  60K Apr 30 11:16 vboxnetflt.ko
```

**Comment by dileks** [comment]
Debian's latest 5.10 kernel works, too.
```
root# dkms status -m virtualbox
virtualbox, 6.1.20, 5.10.0-6-amd64, x86_64: installed
virtualbox, 6.1.20, 5.12.0-1-amd64-clang12-lto, x86_64: installed
```

**Comment by torvic9** [comment]
> seems to be a local or distro specific problem.

You are probably right, but I don't know what could be the cause :(
(It's not a distro clang, but one built with build-llvm.py script.)

**Comment by dileks** [comment]
I was able to start my `FreeDOS v1.2` image in VBox-Qt-Gui.
```
root# modprobe vboxdrv
root# lsmod | grep vbox
vboxdrv               557056  0
```

**Comment by dileks** [comment]
@torvic9 

Dunno Arch Linux en detail and its vbox dkms.conf.
You can try to adapt my above modifications.

Anyway, it is good to see a `Clang-LTO enabled Linux-kernel` works with `VirtualBox v6.1.20`.

**Comment by torvic9** [comment]
Yes, I'm going to add `V=1` to the (otherwise very similar) make command in order to hopefully get more info.
I'll report back.

**Comment by dileks** [comment]
Just DO it :-).

**Comment by torvic9** [comment]
`V=1` does nothing.

@dileks, do you know if it is possible to disable LTO for the virtualbox modules only, maybe something like `-fno-lto`?
It seems to automatically enable it:

```
  AR [M]  /home/unsorted/linux512-vd-virtualbox-modules/src/vboxhost/6.1.20_OSE/build/vboxdrv/vboxdrv.o
  LTO [M] /home/unsorted/linux512-vd-virtualbox-modules/src/vboxhost/6.1.20_OSE/build/vboxdrv/vboxdrv.lto.o
ld.lld: error: Permission denied
make[3]: *** [scripts/Makefile.modpost:121: [...]
```

EDIT: Nevermind! KBUILD_VERBOSE and/or VBOX_LNX_VERBOSE has to be set to 1 to get verbose output.

**Comment by dileks** [comment]
@torvic9 

Dunno if this is a good idea to build the vbox module w/o LTO.

Interesting that passing `V=1` does not show full make-lines when building vbox-dkms.

Hmmm, `6.1.20_OSE` is that from upstream?

**Comment by torvic9** [comment]
V=1 gets abbreviated to V=, probably a configuration/setup issue on my end.

The actual error message is:
```make -f ./scripts/Makefile.modpost
  ld.lld -m elf_x86_64 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5   
-r -o /home/unsorted/linux512-vd-virtualbox-modules/src/vboxhost/6.1.20_OSE/build/vboxdrv/vboxdrv.lto.o
 --whole-archive /home/unsorted/linux512-vd-virtualbox-modules/src/vboxhost/6.1.20_OSE/build/vboxdrv/vboxdrv.o
ld.lld: error: Permission denied
```

(yes, upstream via Arch - and I just saw that we have a new 6.1.22 release now)

EDIT: I'm giving this a break, as the LTO error is most certainly an issue on my side and not with either clang, dkms or vbox. Thanks for your help!

**Comment by ColinIanKing** [comment]
Perhaps the /home/unsorted/linux512-vd-virtualbox-modules/src/vboxhost/6.1.20_OSE/build/vboxdrv/vboxdrv.o obj file can't be overwritten. try manually removing it before kicking off a build.

**Comment by torvic9** [comment]
The build directory is auto-cleaned on each try.
Could it be this maybe: `--thinlto-cache-dir=.thinlto-cache` ?
I cannot find such a directory anywhere.

**Comment by nathanchance** [comment]
What folder are you running the dkms command in? It is possible that the ThinLTO cache is being created there, rather than in the build folder, and the permissions might not be right. You can try to confirm if it is that by just removing that line from the Makefile; it is just to speed up incremental builds.

**Comment by torvic9** [comment]
I'm using Arch's `makepkg` system, which, when executed runs dkms in $BUILDDIR which is a user choice. Normally, I simply use /tmp with 777 permissions.
However, I suspect the VBox build system tries to create the thinlto cache folder in the VBox source directory, which is not user-writable as it resides in `/usr/src` and is only symlinked by dkms on build.
I'm now looking to add `-Wl,--thinlto-cache-dir=/tmp` to LDFLAGS, but I don't know how this can be done by editing the Makefiles. EDIT: added it to EXTRA_LDFLAGS but lld complains that it is an unknown argument. EDIT2: it has to be used without -Wl -- it now goes one step further until an other permission denied occurs...

> by just removing that line from the Makefile

Which line do you mean?

**Comment by torvic9** [comment]
Please do not waste your time with my setup issue...

IMO this issue can be closed, Sedat showed that it works.
This is more likely something for the dkms people.
Thanks @ all.

**Comment by torvic9** [comment]
Yes! 
I finally solved the issue by dirty-hacking the relevant `scripts/Makefile.xxx` kernel files, and adding `--thinlto-cache-dir=/tmp/thinlto` to their revelant LDFLAGS settings.

**Comment by torvic9** [comment]
For future reference, especially for Arch users who want to keep using the native build system, here is a dirty kernel diff for 5.12 that works around the issue:

```
diff --git a/scripts/Makefile.lib b/scripts/Makefile.lib
index 8cd67b1..771ba34 100644
--- a/scripts/Makefile.lib
+++ b/scripts/Makefile.lib
@@ -186,6 +186,11 @@ endif
 part-of-module = $(if $(filter $(basename $@).o, $(real-obj-m)),y)
 quiet_modtag = $(if $(part-of-module),[M],   )
 
+# Make sure that the ThinLTO cache is located in a user-writable location
+ifdef CONFIG_LTO_CLANG_THIN
+EXTRA_LDFLAGS += --thinlto-cache-dir=/tmp/thinlto
+endif # CONFIG_LTO_CLANG_THIN
+
 modkern_cflags =                                          \
 	$(if $(part-of-module),                           \
 		$(KBUILD_CFLAGS_MODULE) $(CFLAGS_MODULE), \
diff --git a/scripts/Makefile.modfinal b/scripts/Makefile.modfinal
index 735e11e..619e6cd 100644
--- a/scripts/Makefile.modfinal
+++ b/scripts/Makefile.modfinal
@@ -35,6 +35,11 @@ ifdef CONFIG_LTO_CLANG
 # avoid a second slow LTO link
 prelink-ext := .lto
 
+# Make sure that the ThinLTO cache is located in a user-writable location
+ifdef CONFIG_LTO_CLANG_THIN
+KBUILD_LDFLAGS += --thinlto-cache-dir=/tmp/thinlto
+endif # CONFIG_LTO_CLANG_THIN
+
 # ELF processing was skipped earlier because we didn't have native code,
 # so let's now process the prelinked binary before we link the module.
 
-- 
```

[--> Link to full patch file](https://github.com/torvic9/linux512-vd/blob/master/2014-scripts-makefiles-put-thinlto-cache-in-tmp-when-usin.patch)

**Comment by dileks** [comment]
Normally, you have a `.thinlto` directory in your kernel build-directory.

**Comment by torvic9** [comment]
That directory is owned by root on Arch and not writable by the user.
It's in /lib/modules/-kernelname- and symlinked to /usr/src.
The alternative would be to copy the build dir to another location and make dkms point to it, but that's IMO more complicated (indeed, I haven't been successful with that).

(Note: I mean a kernel that is already properly installed with pacman)

**Comment by dileks** [comment]
Maybe that `.thinlto` dir location should be user-configurable via kbuild/kconfig?

Alternatively, you use `sudo dkms ...`?

**Comment by torvic9** [comment]
Arch uses `fakeroot dkms`, for the Arch default kernel: https://github.com/archlinux/svntogit-community/blob/packages/virtualbox-host-modules-arch/trunk/PKGBUILD

> Maybe that .thinlto dir location should be user-configurable via kbuild/kconfig?

Yes. I will create a patch to make it configurable.

**Comment by dileks** [comment]
`fakeroot` is an alternative (which I do no more use in my kernel build-script).

**Comment by torvic9** [comment]
Here is a new diff. I really don't know much about the whole kernel things, but it seems to work in a first test:

```diff
diff --git a/Makefile b/Makefile
index 78b0941..70d4e0d 100644
--- a/Makefile
+++ b/Makefile
@@ -904,7 +904,8 @@ endif
 ifdef CONFIG_LTO_CLANG
 ifdef CONFIG_LTO_CLANG_THIN
 CC_FLAGS_LTO	:= -flto=thin -fsplit-lto-unit
-KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(extmod-prefix).thinlto-cache
+export thinlto-dir	= $(if $(CONFIG_LTO_CLANG_THIN_CACHEDIR),$(CONFIG_LTO_CLANG_THIN_CACHEDIR)/)
+KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(thinlto-dir)$(extmod-prefix).thinlto-cache
 else
 CC_FLAGS_LTO	:= -flto
 endif
diff --git a/arch/Kconfig b/arch/Kconfig
index ecfd352..ae54c50 100644
--- a/arch/Kconfig
+++ b/arch/Kconfig
@@ -690,6 +690,16 @@ config LTO_CLANG_THIN
 	    https://clang.llvm.org/docs/ThinLTO.html
 
 	  If unsure, say Y.
+
+config LTO_CLANG_THIN_CACHEDIR
+	string "Clang ThinLTO cache directory"
+	depends on LTO_CLANG_THIN
+	default ""
+	help
+	  This option allows users to choose a directory that stores
+	  Clang's ThinLTO cache.
+	  Leave empty for default.
+
 endchoice
 
 config HAVE_ARCH_WITHIN_STACK_FRAMES
diff --git a/scripts/Makefile.lib b/scripts/Makefile.lib
index 8cd67b1..bed63db 100644
--- a/scripts/Makefile.lib
+++ b/scripts/Makefile.lib
@@ -186,6 +186,10 @@ endif
 part-of-module = $(if $(filter $(basename $@).o, $(real-obj-m)),y)
 quiet_modtag = $(if $(part-of-module),[M],   )
 
+ifdef CONFIG_LTO_CLANG_THIN
+KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(thinlto-dir)$(extmod-prefix).thinlto-cache
+endif
+
 modkern_cflags =                                          \
 	$(if $(part-of-module),                           \
 		$(KBUILD_CFLAGS_MODULE) $(CFLAGS_MODULE), \
diff --git a/scripts/Makefile.modfinal b/scripts/Makefile.modfinal
index 735e11e..da0995c 100644
--- a/scripts/Makefile.modfinal
+++ b/scripts/Makefile.modfinal
@@ -35,6 +35,10 @@ ifdef CONFIG_LTO_CLANG
 # avoid a second slow LTO link
 prelink-ext := .lto
 
+ifdef CONFIG_LTO_CLANG_THIN
+KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(thinlto-dir)$(extmod-prefix).thinlto-cache
+endif
+
 # ELF processing was skipped earlier because we didn't have native code,
 # so let's now process the prelinked binary before we link the module.
 
```

**Comment by torvic9** [comment]
I think this can be closed for now. 
For me, the problem is solved with the above patch.
(PS: thanks @nickdesaulniers for the invitation to ClangBuiltLinux, but I do not have enough knowledge to help you with your project.)

**Comment by nathanchance** [comment]
I wonder if it is worth upstreaming that diff?

**Comment by StatusCode404** [comment]
Hi All, I'm experiencing a similar problem and thought it was a Vbox issue and filed a bug with them....
[https://www.virtualbox.org/ticket/20425](url)

So who rightfully owns this problem?  Is it Virtualbox?

@torvic9 is proposing to close this for now, but what is the procedure to fix this for the masses who are now trying Clang/llvm thin lto'ed kernels?
Perhaps someone could outline in a reply the steps to resolve the problem?  So just to be clear, we cannot run vbox guest vms on host kernels built with clang/llvm with thin lto.  In my case, switching the default "cc" didn't fix the problem and "gcc" looks like it is hardcoded when trying to build the vboxdrv modules.

Thanks in advance if someone could write up the work-around procedure!

**Comment by nathanchance** [comment]
@StatusCode404 it is most likely something with DKMS: https://github.com/dell/dkms/issues/124

I have no idea what the workaround is. I was able to build the VirtualBox module without DKMS [here](https://github.com/ClangBuiltLinux/linux/issues/1104#issuecomment-680740128), that might work for you.

**Comment by torvic9** [comment]
> 
> Thanks in advance if someone could write up the work-around procedure!

Hi,
you have to tell DKMS to use Clang instead of GCC.
It is not an issue with VBox but rather with DKMS.
As documented in the manpage, you can use `MAKE[0]` in the file `dkms.conf` for that.
A simple example from my Arch PKGBUILD:
```
    LLVM_UTILS="CC=$CLPF/clang CXX=$CLPF/clang++ LD=$CLPF/ld.lld \
     AS=$CLPF/llvm-as AR=$CLPF/llvm-ar NM=$CLPF/llvm-nm \
     OBJCOPY=$CLPF/llvm-objcopy OBJSIZE=$CLPF/llvm-size \
     STRIP=$CLPF/llvm-strip"
    echo "MAKE[0]=\"make ${LLVM_UTILS} KERNELRELEASE=${_kernver}\"" >> $srcdir/dkms.conf
```

(In the above example, `$CLPF` is simply pointing to the path of the toolchain, whereas `$LLVM_UTILS` regroups all the different llvm/clang tools that are needed.)

**Comment by StatusCode404** [comment]
Thanks for the pointer!

**Comment by v-fox** [comment]
@nathanchance 
> I wonder if it is worth upstreaming that diff?

This doesn't just breaks VB in DKMS on Arch, it breaks all 3rd-party module packages on Open Build Service, meaning that it breaks all 3rd-party, like zfs and nvidia-driver, in most/all distros. I've been using similar hack for 5.12 but it broke in 5.13. So it is very much worth upstreaming.

**Comment by StatusCode404** [comment]
I agree, the fix needs to be able to cater for both gcc and clang-llvm-lld.  Figure it out during execution and use the right tool.

Failing to do this will mean little adoption of clang-built linux kernels which seems to perform better in benchmarks.

**Comment by torvic9** [comment]
@v-fox , well I can try to send the patch upstream for 5.14-rc1. Still, I think it's not really a kernel issue so I guess the chance of acceptance are small... anyone tried using `KBUILD_EXTMOD` instead?

As for gcc, no idea, there is currently no upstream LTO support for it unless I'm mistaken.

**Comment by v-fox** [comment]
> well I can try to send the patch upstream for 5.14-rc1. Still, I think it's not really a kernel issue so I guess the chance of acceptance are small... anyone tried using `KBUILD_EXTMOD` instead?
> 
> As for gcc, no idea, there is currently no upstream LTO support for it unless I'm mistaken.

That is very much kernel's issue. Neither using clang nor enabling LTO should make out-of-tree modules unbuildable, deficiencies should be fixed. I rebased your patch for 5.13 for myself with using '/tmp' by default and it seems to work fine on OBS now. Putting toolchain overrides into every out-of-tree module package is still a necessity though but that's a separate issue. Not sure if it's possible to make out-of-tree modules somehow inherit toolchain settings from kernel.

**Comment by torvic9** [comment]
> Not sure if it's possible to make out-of-tree modules somehow inherit toolchain settings from kernel.

That would be the "correct" way to go in my opinion - but rather on the DKMS side.
Is there a command that can extract this information from binaries (readelf?)?

Anyway, if people think that it's worth upstreaming, then I'm going to do so once 5.14 is mainlined.

**Comment by torvic9** [comment]
Here is a rebased version (based on Linus' tree):
https://gitlab.com/torvic9/linux513-vd/-/blob/master/unused/Kbuild-add-option-for-choosing-a-ThinLTO-cache-direc.patch

Feel free to test and report.$

EDIT: **major oops!** I accidently removed a line. Do not use this, I will put up a rectified version.

**Comment by torvic9** [comment]
Fixed patch (as a gist):
https://gist.github.com/torvic9/17c6a86ca4345d62e7907c96231c2775

**Comment by nickdesaulniers** [comment]
I sent dkms [a patch](https://github.com/dell/dkms/pull/169).

**Comment by nickdesaulniers** [comment]
This should be fixed as of [DKMS 3.0.2](https://github.com/dell/dkms/commit/29c9e1f7b107c470a38024e626852428469b241f).
https://github.com/dell/dkms/commit/6ddb09145930b03c88e63f5930e718a33501024d

Note: there's also a requirement for dkms that `clang` be accesible from a `$PATH` allowlist.
https://github.com/dell/dkms/issues/124#issuecomment-955194338
https://github.com/dell/dkms/blob/41efbd50f635af0ec230478525e5be56d6003896/dkms.in#L2163-L2164
